#!/bin/bash
for (( c=1; c<=10; c++ ))
do 	
	python ssl_training.py --experiment_config_path ./configs/models/ssl/simclr/simclr_mobiact.yaml --dataset mobi_act --augmentations_path configs/augmentations/jit_scal_rot.yaml --framework simclr --model transformer --num-workers 16  --linear_eval --xai_study --fine_tuning --fine_tuning_ckpt_path model_weights_papers/xai/simclr/mobi_act-transformer-2022-07-29_18_05_40_335746/last.ckpt  --randomly_masked_channels_test 0 --test_occlusion --seed $c;
	python ssl_training.py --experiment_config_path ./configs/models/ssl/simclr/simclr_mobiact.yaml --dataset mobi_act --augmentations_path configs/augmentations/jit_scal_rot.yaml --framework simclr --model transformer --num-workers 16  --linear_eval --xai_study --fine_tuning --fine_tuning_ckpt_path model_weights_papers/xai/simclr/mobi_act-transformer-2022-07-29_18_05_40_335746/last.ckpt  --randomly_masked_channels_test 1 --test_occlusion --seed $c; 
	python ssl_training.py --experiment_config_path ./configs/models/ssl/simclr/simclr_mobiact.yaml --dataset mobi_act --augmentations_path configs/augmentations/jit_scal_rot.yaml --framework simclr --model transformer --num-workers 16  --linear_eval --xai_study --fine_tuning --fine_tuning_ckpt_path model_weights_papers/xai/simclr/mobi_act-transformer-2022-07-29_18_05_40_335746/last.ckpt  --randomly_masked_channels_test 2 --test_occlusion --seed $c;
	python ssl_training.py --experiment_config_path ./configs/models/ssl/simclr/simclr_mobiact.yaml --dataset mobi_act --augmentations_path configs/augmentations/jit_scal_rot.yaml --framework simclr --model transformer --num-workers 16  --linear_eval --xai_study --fine_tuning --fine_tuning_ckpt_path model_weights_papers/xai/simclr/mobi_act-transformer-2022-07-29_18_05_40_335746/last.ckpt  --randomly_masked_channels_test 3 --test_occlusion --seed $c;
	python ssl_training.py --experiment_config_path ./configs/models/ssl/simclr/simclr_mobiact.yaml --dataset mobi_act --augmentations_path configs/augmentations/jit_scal_rot.yaml --framework simclr --model transformer --num-workers 16  --linear_eval --xai_study --fine_tuning --fine_tuning_ckpt_path model_weights_papers/xai/simclr/mobi_act-transformer-2022-07-29_18_05_40_335746/last.ckpt  --randomly_masked_channels_test 4 --test_occlusion --seed $c;
	python ssl_training.py --experiment_config_path ./configs/models/ssl/simclr/simclr_mobiact.yaml --dataset mobi_act --augmentations_path configs/augmentations/jit_scal_rot.yaml --framework simclr --model transformer --num-workers 16  --linear_eval --xai_study --fine_tuning --fine_tuning_ckpt_path model_weights_papers/xai/simclr/mobi_act-transformer-2022-07-29_18_05_40_335746/last.ckpt  --randomly_masked_channels_test 5 --test_occlusion --seed $c;
done
for (( c=1; c<=10; c++ ))
do 
	python ssl_training.py --experiment_config_path ./configs/models/ssl/vicreg/vicreg_mobiact.yaml --dataset mobi_act --augmentations_path configs/augmentations/jit_scal_rot.yaml --framework vicreg --model transformer --num-workers 16  --linear_eval --xai_study --fine_tuning --fine_tuning_ckpt_path model_weights_papers/xai/vicreg/mobi_act-transformer-2022-09-05_10_13_38_262428/last.ckpt --randomly_masked_channels_test 0 --test_occlusion --seed $c;
	python ssl_training.py --experiment_config_path ./configs/models/ssl/vicreg/vicreg_mobiact.yaml --dataset mobi_act --augmentations_path configs/augmentations/jit_scal_rot.yaml --framework vicreg --model transformer --num-workers 16  --linear_eval --xai_study --fine_tuning --fine_tuning_ckpt_path model_weights_papers/xai/vicreg/mobi_act-transformer-2022-09-05_10_13_38_262428/last.ckpt --randomly_masked_channels_test 1 --test_occlusion --seed $c;
	python ssl_training.py --experiment_config_path ./configs/models/ssl/vicreg/vicreg_mobiact.yaml --dataset mobi_act --augmentations_path configs/augmentations/jit_scal_rot.yaml --framework vicreg --model transformer --num-workers 16  --linear_eval --xai_study --fine_tuning --fine_tuning_ckpt_path model_weights_papers/xai/vicreg/mobi_act-transformer-2022-09-05_10_13_38_262428/last.ckpt --randomly_masked_channels_test 2 --test_occlusion --seed $c;
	python ssl_training.py --experiment_config_path ./configs/models/ssl/vicreg/vicreg_mobiact.yaml --dataset mobi_act --augmentations_path configs/augmentations/jit_scal_rot.yaml --framework vicreg --model transformer --num-workers 16  --linear_eval --xai_study --fine_tuning --fine_tuning_ckpt_path model_weights_papers/xai/vicreg/mobi_act-transformer-2022-09-05_10_13_38_262428/last.ckpt --randomly_masked_channels_test 3 --test_occlusion --seed $c;
	python ssl_training.py --experiment_config_path ./configs/models/ssl/vicreg/vicreg_mobiact.yaml --dataset mobi_act --augmentations_path configs/augmentations/jit_scal_rot.yaml --framework vicreg --model transformer --num-workers 16  --linear_eval --xai_study --fine_tuning --fine_tuning_ckpt_path model_weights_papers/xai/vicreg/mobi_act-transformer-2022-09-05_10_13_38_262428/last.ckpt --randomly_masked_channels_test 4 --test_occlusion --seed $c;
	python ssl_training.py --experiment_config_path ./configs/models/ssl/vicreg/vicreg_mobiact.yaml --dataset mobi_act --augmentations_path configs/augmentations/jit_scal_rot.yaml --framework vicreg --model transformer --num-workers 16  --linear_eval --xai_study --fine_tuning --fine_tuning_ckpt_path model_weights_papers/xai/vicreg/mobi_act-transformer-2022-09-05_10_13_38_262428/last.ckpt --randomly_masked_channels_test 5 --test_occlusion --seed $c;
done
for (( c=1; c<=10; c++ ))
do	
	python ssl_training.py --experiment_config_path ./configs/models/supervised/transformer_mobiact.yaml --dataset mobi_act --supervised --model transformer --num-workers 16  --linear_eval --xai_study --randomly_masked_channels_test 0 --test_occlusion --seed $c;
	python ssl_training.py --experiment_config_path ./configs/models/supervised/transformer_mobiact.yaml --dataset mobi_act --supervised --model transformer --num-workers 16  --linear_eval --xai_study --randomly_masked_channels_test 1 --test_occlusion --seed $c;
	python ssl_training.py --experiment_config_path ./configs/models/supervised/transformer_mobiact.yaml --dataset mobi_act --supervised --model transformer --num-workers 16  --linear_eval --xai_study --randomly_masked_channels_test 2 --test_occlusion --seed $c;
	python ssl_training.py --experiment_config_path ./configs/models/supervised/transformer_mobiact.yaml --dataset mobi_act --supervised --model transformer --num-workers 16  --linear_eval --xai_study --randomly_masked_channels_test 3 --test_occlusion --seed $c;
	python ssl_training.py --experiment_config_path ./configs/models/supervised/transformer_mobiact.yaml --dataset mobi_act --supervised --model transformer --num-workers 16  --linear_eval --xai_study --randomly_masked_channels_test 4 --test_occlusion --seed $c;
	python ssl_training.py --experiment_config_path ./configs/models/supervised/transformer_mobiact.yaml --dataset mobi_act --supervised --model transformer --num-workers 16  --linear_eval --xai_study --randomly_masked_channels_test 5 --test_occlusion --seed $c;	
done