#!/bin/bash
for (( c=1; c<=10; c++ ))
do 	
	python ssl_training.py --experiment_config_path ./configs/models/ssl/simclr/simclr_uci.yaml --dataset uci_har --augmentations_path configs/augmentations/jit_scal_perm.yaml --framework simclr --model transformer --num-workers 16 --linear_eval --xai_study --fine_tuning --fine_tuning_ckpt_path model_weights_papers/xai/simclr/uci_har-transformer-2022-08-25_15_54_30_790398/last.ckpt --randomly_masked_channels_test 0 --test_occlusion --seed $c;
	python ssl_training.py --experiment_config_path ./configs/models/ssl/simclr/simclr_uci.yaml --dataset uci_har --augmentations_path configs/augmentations/jit_scal_perm.yaml --framework simclr --model transformer --num-workers 16 --linear_eval --xai_study --fine_tuning --fine_tuning_ckpt_path model_weights_papers/xai/simclr/uci_har-transformer-2022-08-25_15_54_30_790398/last.ckpt --randomly_masked_channels_test 1 --test_occlusion --seed $c;
	python ssl_training.py --experiment_config_path ./configs/models/ssl/simclr/simclr_uci.yaml --dataset uci_har --augmentations_path configs/augmentations/jit_scal_perm.yaml --framework simclr --model transformer --num-workers 16 --linear_eval --xai_study --fine_tuning --fine_tuning_ckpt_path model_weights_papers/xai/simclr/uci_har-transformer-2022-08-25_15_54_30_790398/last.ckpt --randomly_masked_channels_test 2 --test_occlusion --seed $c;
	python ssl_training.py --experiment_config_path ./configs/models/ssl/simclr/simclr_uci.yaml --dataset uci_har --augmentations_path configs/augmentations/jit_scal_perm.yaml --framework simclr --model transformer --num-workers 16 --linear_eval --xai_study --fine_tuning --fine_tuning_ckpt_path model_weights_papers/xai/simclr/uci_har-transformer-2022-08-25_15_54_30_790398/last.ckpt --randomly_masked_channels_test 3 --test_occlusion --seed $c;
	python ssl_training.py --experiment_config_path ./configs/models/ssl/simclr/simclr_uci.yaml --dataset uci_har --augmentations_path configs/augmentations/jit_scal_perm.yaml --framework simclr --model transformer --num-workers 16 --linear_eval --xai_study --fine_tuning --fine_tuning_ckpt_path model_weights_papers/xai/simclr/uci_har-transformer-2022-08-25_15_54_30_790398/last.ckpt --randomly_masked_channels_test 4 --test_occlusion --seed $c;
	python ssl_training.py --experiment_config_path ./configs/models/ssl/simclr/simclr_uci.yaml --dataset uci_har --augmentations_path configs/augmentations/jit_scal_perm.yaml --framework simclr --model transformer --num-workers 16 --linear_eval --xai_study --fine_tuning --fine_tuning_ckpt_path model_weights_papers/xai/simclr/uci_har-transformer-2022-08-25_15_54_30_790398/last.ckpt --randomly_masked_channels_test 5 --test_occlusion --seed $c;
done
for (( c=1; c<=10; c++ ))
do 
	python ssl_training.py --experiment_config_path ./configs/models/ssl/vicreg/vicreg_uci.yaml --dataset uci_har --augmentations_path configs/augmentations/jit_scal_perm.yaml --framework vicreg --model transformer --num-workers 16 --linear_eval --xai_study --fine_tuning --fine_tuning_ckpt_path model_weights_papers/xai/vicreg/uci_har-transformer-2022-09-05_10_14_23_223035/last.ckpt --randomly_masked_channels_test 0 --test_occlusion --seed $c;
	python ssl_training.py --experiment_config_path ./configs/models/ssl/vicreg/vicreg_uci.yaml --dataset uci_har --augmentations_path configs/augmentations/jit_scal_perm.yaml --framework vicreg --model transformer --num-workers 16 --linear_eval --xai_study --fine_tuning --fine_tuning_ckpt_path model_weights_papers/xai/vicreg/uci_har-transformer-2022-09-05_10_14_23_223035/last.ckpt --randomly_masked_channels_test 1 --test_occlusion --seed $c;
	python ssl_training.py --experiment_config_path ./configs/models/ssl/vicreg/vicreg_uci.yaml --dataset uci_har --augmentations_path configs/augmentations/jit_scal_perm.yaml --framework vicreg --model transformer --num-workers 16 --linear_eval --xai_study --fine_tuning --fine_tuning_ckpt_path model_weights_papers/xai/vicreg/uci_har-transformer-2022-09-05_10_14_23_223035/last.ckpt --randomly_masked_channels_test 2 --test_occlusion --seed $c;
	python ssl_training.py --experiment_config_path ./configs/models/ssl/vicreg/vicreg_uci.yaml --dataset uci_har --augmentations_path configs/augmentations/jit_scal_perm.yaml --framework vicreg --model transformer --num-workers 16 --linear_eval --xai_study --fine_tuning --fine_tuning_ckpt_path model_weights_papers/xai/vicreg/uci_har-transformer-2022-09-05_10_14_23_223035/last.ckpt --randomly_masked_channels_test 3 --test_occlusion --seed $c;
	python ssl_training.py --experiment_config_path ./configs/models/ssl/vicreg/vicreg_uci.yaml --dataset uci_har --augmentations_path configs/augmentations/jit_scal_perm.yaml --framework vicreg --model transformer --num-workers 16 --linear_eval --xai_study --fine_tuning --fine_tuning_ckpt_path model_weights_papers/xai/vicreg/uci_har-transformer-2022-09-05_10_14_23_223035/last.ckpt --randomly_masked_channels_test 4 --test_occlusion --seed $c;
	python ssl_training.py --experiment_config_path ./configs/models/ssl/vicreg/vicreg_uci.yaml --dataset uci_har --augmentations_path configs/augmentations/jit_scal_perm.yaml --framework vicreg --model transformer --num-workers 16 --linear_eval --xai_study --fine_tuning --fine_tuning_ckpt_path model_weights_papers/xai/vicreg/uci_har-transformer-2022-09-05_10_14_23_223035/last.ckpt --randomly_masked_channels_test 5 --test_occlusion --seed $c;
done
for (( c=1; c<=10; c++ ))
do	
	python ssl_training.py --experiment_config_path ./configs/models/supervised/transformer_uci.yaml --dataset uci_har  --model transformer --num-workers 16 --supervised --linear_eval --xai_study --randomly_masked_channels_test 0 --test_occlusion --seed $c;
	python ssl_training.py --experiment_config_path ./configs/models/supervised/transformer_uci.yaml --dataset uci_har  --model transformer --num-workers 16 --supervised --linear_eval --xai_study --randomly_masked_channels_test 1 --test_occlusion --seed $c; 
	python ssl_training.py --experiment_config_path ./configs/models/supervised/transformer_uci.yaml --dataset uci_har  --model transformer --num-workers 16 --supervised --linear_eval --xai_study --randomly_masked_channels_test 2 --test_occlusion --seed $c; 
	python ssl_training.py --experiment_config_path ./configs/models/supervised/transformer_uci.yaml --dataset uci_har  --model transformer --num-workers 16 --supervised --linear_eval --xai_study --randomly_masked_channels_test 3 --test_occlusion --seed $c; 
	python ssl_training.py --experiment_config_path ./configs/models/supervised/transformer_uci.yaml --dataset uci_har  --model transformer --num-workers 16 --supervised --linear_eval --xai_study --randomly_masked_channels_test 4 --test_occlusion --seed $c; 
	python ssl_training.py --experiment_config_path ./configs/models/supervised/transformer_uci.yaml --dataset uci_har  --model transformer --num-workers 16 --supervised --linear_eval --xai_study --randomly_masked_channels_test 5 --test_occlusion --seed $c;
done