uci_har:
  train: './sampled_data/uci_har/uci_smartphones/train'
  val: './sampled_data/uci_har/uci_smartphones/val'
  test: './sampled_data/uci_har/uci_smartphones/test'
  n_classes: 6
  class_names: ['WALKING', 'WALKING_UPSTAIRS', 'WALKING_DOWNSTAIRS', 'SITTING', 'STANDING', 'LAYING']
  devices: ['acc_X', 'acc_Y', 'acc_Z', 'gyro_X', 'gyro_Y', 'gyro_Z']
  main_metric: f1-score
  cross-subject: './cs_data/uci_har/uci_smartphones/'
  act_to_type:
    WALKING: 'active'
    WALKING_UPSTAIRS: 'active'
    WALKING_DOWNSTAIRS: 'active'
    SITTING: 'stable'
    STANDING: 'stable'
    LAYING: 'stable'
  type_encoding :
    stable: 0
    active: 1


usc_had: 
  train: './sampled_data/usc_had/usc_had/train'
  val: './sampled_data/usc_had/usc_had/test'
  test: './sampled_data/usc_had/usc_had/test'
  n_classes: 12
  class_names: ['Walking Forward', 'Walking Left', 'Walking Right', 'Walking Upstairs', 'Walking Downstairs', 'Running Forward', 'Jumping Up', 'Sitting', 'Standing', 'Sleeping', 'Elevator Up', 'Elevator Down']
  devices: ["acc_x, w/ unit g (gravity)", "acc_y, w/ unit g", "acc_z, w/ unit g", "gyro_x, w/ unit dps (degrees per second)", "gyro_y, w/ unit dps", "gyro_z, w/ unit dps"]
  main_metric: f1-score
  cross-subject: './cs_data/usc_had/usc_had/'


mobi_act:
  train: './sampled_data/mobi_act/mobi_act/train'
  val: './sampled_data/mobi_act/mobi_act/val'
  test: './sampled_data/mobi_act/mobi_act/test'
  n_classes: 11
  class_names: ['Standing', 'Walking', 'Jogging', 'Jumping', 'Stairs up', 'Stairs down', 'Stand to sit(sit on chair)', 'Sitting on chair', 'Sit to stand(chair up)', 'Car-step in', 'Car-step out']
  devices: ['acc_x', 'acc_y', 'acc_z', 'gyro_x', 'gyro_y', 'gyro_z']
  main_metric: f1-score
  cross-subject: './cs_data/mobi_act/mobi_act/' 
  act_to_type:
    Car-step in: 'transition'
    Car-step out: 'transition'
    Jogging: 'active'
    Jumping: 'active'
    Sit to stand(chair up): 'transition'
    Sitting on chair: 'stable'
    Stairs down: 'active'
    Stairs up: 'active'
    Stand to sit(sit on chair): 'transition'
    Standing: 'stable'
    Walking: 'active'
  type_encoding :
    stable: 0
    active: 1
    transition: 2


pamap2:
  train: './sampled_data/pamap2_heart/pamap2/train'
  val: './sampled_data/pamap2_heart/pamap2/val'
  test: './sampled_data/pamap2_heart/pamap2/test'
  n_classes: 12
  class_names: ['lying', 'sitting', 'standing', 'walking', 'running','cycling','Nordic walking','ascending stairs','descending stairs','vacuum cleaning','ironing']
  devices: ['heartrate','hand_acc1_X','hand_acc1_Y','hand_acc1_Z','hand_gyro_X','hand_gyro_Y','hand_gyro_Z','hand_mg_X','hand_mg_Y','hand_mg_Z','body_acc1_X','body_acc1_Y','body_acc1_Z','body_gyro_X','body_gyro_Y','body_gyro_Z','body_mg_X','body_mg_Y','body_mg_Z','ankle_acc1_X','ankle_acc1_Y','ankle_acc1_Z','ankle_gyro_X','ankle_gyro_Y','ankle_gyro_Z','ankle_mg_X','ankle_mg_Y','ankle_mg_Z']
  main_metric: f1-score