experiment:
  seed: 28
  num_epochs_ssl: 200
  num_epochs_fine_tuning: 100
  batch_size_fine_tuning: 128

model:
  transformer:
    from_module: transformer
    encoder_class_name: Transformer
    encoder_name: transformer
    args: []
    kwargs:
      in_channels: 28
      max_len: 171

      kernel_size: 5
      out_channels: [64, 128, 256]
      
      num_head: 4
      num_layers: 8

      lr: 0.0001
      optimizer_name: "adam"
  ssl:
      args: []
      kwargs:
        ssl_lr: 0.0001
        projection_hidden: 256
        embedding_size: 256
        
        temperature: 0.1
        ssl_batch_size: 64
        optimizer_name_ssl: "lars"