program: ssl_training.py
method: grid
project: sweep_transformer_pamap2_heart
entity: sensor_har
metric:
  name: test_f1-score
  goal: maximize
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--experiment_config_path"
  - "configs/models/supervised/transformer_pamap2.yaml"
  - "--dataset"
  - "pamap2"
  - "--model"
  - "transformer"
  - "--supervised"
  - "--linear_eval"
  - "--num-workers"
  - "16"
  - "--sweep"
  
  
parameters:
  # General configs
  num_epochs_ssl: 
    values: [0]
  num_epochs_fine_tuning:
    values: [50]
  batch_size_fine_tuning:
    values: [128]

  # transformer configs (will overwrite kwargs in supervised model definition)
  model.kernel_size:
    values: [3, 5]
  model.out_channels:
    values: [[32, 64, 128], [64, 128, 256]]
  model.num_head:
    values: [2, 4, 6, 8]
  model.num_layers:
    values: [2, 4, 6, 8]
  model.lr:
    values: [0.0001]
  